ALTER TABLE players ADD COLUMN pac INTEGER NOT NULL DEFAULT 50;
ALTER TABLE players ADD COLUMN sho INTEGER NOT NULL DEFAULT 50;
ALTER TABLE players ADD COLUMN pas INTEGER NOT NULL DEFAULT 50;
ALTER TABLE players ADD COLUMN dri INTEGER NOT NULL DEFAULT 50;
ALTER TABLE players ADD COLUMN def INTEGER NOT NULL DEFAULT 50;
ALTER TABLE players ADD COLUMN phy INTEGER NOT NULL DEFAULT 50;
